server:
  protocol: http
  host: 127.0.0.1
  port: 7150

logger:
  level: trace # off, warn, trace, error, info, debug
  format: pretty # json, pretty, compact, full
  ## Crates to log i.e *name of your crate*, sqlx, axum, etc
  crates:
    - "auth"
    - "axum"
    - "sqlx"
    - "tower"
    - "tower-http"

database:
  uri: postgresql://postgres:postgres@localhost:5432/postgres
  username: postgres
  password: postgres
  host: localhost
  port: 5432
  database: postgres
  ssl: false

redis:
  uri: redis://localhost:6379

auth:
  access:
    private_key: config/security/keys/access_key.pem
    public_key: config/security/keys/access_key_pub.pem
    exp: 900 # Seconds 15 minutes
  refresh:
    private_key: config/security/keys/refresh_key.pem
    public_key: config/security/keys/refresh_key_pub.pem
    exp: 2419200 # Seconds 4 Weeks
